version: "3.8"

services:
  api-gateway:
    build: apps/api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "3000:3000"

  hello-world-microservice:
    build: apps/hello-world-microservice
    container_name: hello-world-microservice
    restart: always
    ports:
      - "3001:3001"
