version: "3.8"

services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - api-gateway
      - hello-world-microservice
    network_mode: host

  hello-world-microservice:
    build: apps/hello-world-microservice
    container_name: hello-world-microservice
    network_mode: host

  api-gateway:
    build: api-gateway
    container_name: api-gateway
    network_mode: host
