version: "3.8"

services:
  api-gateway:
    build: apps/api-gateway
    container_name: api-gateway
    restart: always
    network_mode: host

  hello-world-microservice:
    build: apps/hello-world-microservice
    container_name: hello-world-microservice
    restart: always
    network_mode: host
