name: Deploy to Amazon ECS

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY_API_GATEWAY: "api-gateway"
  ECR_REPOSITORY_HELLO_WORLD: "hello-world-microservice"
  ECR_REGISTRY_GLOBAL: "public.ecr.aws/l0w9m4t8"
  ECS_SERVICE: "app-web"
  ECS_CLUSTER: "nestjs-microservices"
  ECS_TASK_DEFINITION: .github/.aws/task-definition.json

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push hello-world microservice image to Amazon ECR
        id: build-hello-image
        env:
          ECR_REGISTRY: ${{ env.ECR_REGISTRY_GLOBAL }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY_HELLO_WORLD }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t hello-world-microservice ./apps/hello-world-microservice
          docker tag hello-world-microservice $ECR_REGISTRY/$ECR_REPOSITORY_HELLO_WORLD:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_HELLO_WORLD:latest
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY_HELLO_WORLD:$IMAGE_TAG" >> $GITHUB_ENV

      # - name: Build, tag, and push api-gateway microservice image to Amazon ECR
      #   id: build-api-image
      #   env:
      #     ECR_REGISTRY: ${{ env.ECR_REGISTRY_GLOBAL }}
      #     ECR_REPOSITORY: ${{ env.ECR_REPOSITORY_API_GATEWAY }}
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build -t api-gateway ./api-gateway
      #     docker tag api-gateway $ECR_REGISTRY/$ECR_REPOSITORY_API_GATEWAY:latest
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY_API_GATEWAY:latest
      #     echo "image=$ECR_REGISTRY/$ECR_REPOSITORY_API_GATEWAY:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Print GitHub environment variables
        run: echo "$GITHUB_ENV"
